### ISSUE TITLE
Trustfactor Lobby Rang Update

### ISSUE THREAD

**Issue by Hotkeyyy** [bluefireoly/HGLaborLobbyRemastered#4]
Vielleicht in der Lobby bei dem Trustfactor Rang irgendein farbiges Zeichen weil es sonst Lost aussieht

**Comment by r0yzer** [comment]
ich finde es reicht wenn man den normalen rang hat damit hacker das nicht so einfach erkennen

**Comment by jakobkmar** [comment]
Hat halt nix mit der Lobby zu tun aber okay.
