### ISSUE TITLE
Items aus den Warp-Menüs gehen ins Inventory

### ISSUE THREAD

**Issue by ghost** [bluefireoly/HGLaborLobbyRemastered#59]
Ist kein schlimmer Bug ich weiß, aber ist mir halt random aufgefallen. Wenn du in ein Menu gehst, kannst du das dortige Item  schnell in deine Hotbar moven und schnell das Fenster schließen. Dann hast du das Item immer noch im Inventar.

**Comment by r0yzer** [comment]
clientside ist das

**Comment by ghost** [comment]
Ja kann gut sein

**Comment by jakobkmar** [comment]
das bringt dir nix, das sind clientside ghost items

**Comment by jakobkmar** [comment]
die verschwinden sobald du irgendwie versuchst mit denen zu interagieren

**Comment by ghost** [comment]
Hab ich später dann auch bemerkt, als ich Helqless schlagen wollte
