### ISSUE TITLE
Idee: Bitte die Lobby nicht in fabric machen

### ISSUE THREAD

**Issue by taito2019** [bluefireoly/HGLaborLobbyRemastered#61]
Norisk bezahlt so viel für den Sever und mag kein fabcric und setz sich für unser Spaß ein also gönnt ihm

**Comment by jakobkmar** [comment]
fabric ist besser aber das hier ist ein spigot projekt was soll dieses issue

**Comment by r0yzer** [comment]
kann man leute irgendwie auf github blocken vom issue erstellen oder so (nur aus interesse)

**Comment by jakobkmar** [comment]
ja geht

**Comment by copyandexecute** [comment]
FABRIC IST AUF KEINEN FALL BESSER HAHAHAHAHAHAHAHAHAHAHAHHAH

**Comment by copyandexecute** [comment]
- [x] Fabric XD

**Comment by copyandexecute** [comment]
@fabric

**Comment by copyandexecute** [comment]
#58

**Comment by jakobkmar** [comment]
@r0yzer wen blocken norisk oder noomacroo oder beide

**Comment by r0yzer** [comment]
beide wenn möglich.

**Comment by taito2019** [comment]
> fabric ist besser aber das hier ist ein spigot projekt was soll dieses issue

Ok sorry habe aber eine Misssion schick mal pls link wo ich das schreiben muss
